name: build swpwn docker image
on:
  push:
    branches: main
    paths:
      - 'build/**'
  schedule:
    - cron: '0 0 1 * *'

jobs:
  all:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        VERSION: ["18.04", "20.04", "22.04"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: beswing
          password: ${{secrets.DOCKER_HUB_TOKEN}}

      - name: Build and push ubuntu ${{ matrix.VERSION }}
        uses: docker/build-push-action@v2
        with:
          file: ./build/ubuntu${{ matrix.VERSION }}/dockerfile
          tags: beswing/swpwn:${{ matrix.VERSION }}
          push: true
