name: build swpwn docker image
on:
  push:
    branches: main
    paths:
      - 'build/**'
  schedule:
    - cron: '0 0 1 * *'

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: beswing
          password: ${{secrets.DOCKER_HUB_TOKEN}}

      - name: Get changed dockerfiles
        id: changed-docker-files
        uses: tj-actions/changed-files@v9
        with:
          files: dockerfile

      - name: Build and push modified dockerfiles
        run: |
          for dockerfile in "${{ steps.changed-docker-files.outputs.all_modified_files }}"; do
            tag=$(basename $(dirname $dockerfile))
            docker build --file $dockerfile --tag $tag .
            docker push beswing/swpwn:$tag
          done
